<?php

namespace Drupal\commerce_fedex\FedEx\ServiceType;

/**
 * Class which returns the class map definition
 * @package
 */
class ShipServiceClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'AdditionalLabelsDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\AdditionalLabelsDetail',
            'Address' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Address',
            'AdrLicenseDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\AdrLicenseDetail',
            'AlcoholDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\AlcoholDetail',
            'AncillaryFeeAndTax' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\AncillaryFeeAndTax',
            'AssociatedShipmentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\AssociatedShipmentDetail',
            'BinaryBarcode' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\BinaryBarcode',
            'BrokerDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\BrokerDetail',
            'CertificateOfOriginDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CertificateOfOriginDetail',
            'ClientDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ClientDetail',
            'CodAddTransportationChargesDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CodAddTransportationChargesDetail',
            'CodDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CodDetail',
            'CodReturnPackageDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CodReturnPackageDetail',
            'CommercialInvoice' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CommercialInvoice',
            'CommercialInvoiceDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CommercialInvoiceDetail',
            'Commodity' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Commodity',
            'CompletedCodDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedCodDetail',
            'CompletedEtdDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedEtdDetail',
            'CompletedHazardousPackageDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedHazardousPackageDetail',
            'CompletedHazardousShipmentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedHazardousShipmentDetail',
            'CompletedHazardousSummaryDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedHazardousSummaryDetail',
            'CompletedHoldAtLocationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedHoldAtLocationDetail',
            'CompletedPackageDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedPackageDetail',
            'CompletedShipmentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedShipmentDetail',
            'CompletedSmartPostDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedSmartPostDetail',
            'CompletedTagDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CompletedTagDetail',
            'ConfigurableLabelReferenceEntry' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ConfigurableLabelReferenceEntry',
            'Contact' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Contact',
            'ContactAndAddress' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ContactAndAddress',
            'ContentRecord' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ContentRecord',
            'CurrencyExchangeRate' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CurrencyExchangeRate',
            'CustomDeliveryWindowDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomDeliveryWindowDetail',
            'CustomDocumentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomDocumentDetail',
            'CustomLabelBarcodeEntry' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomLabelBarcodeEntry',
            'CustomLabelBoxEntry' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomLabelBoxEntry',
            'CustomLabelDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomLabelDetail',
            'CustomLabelGraphicEntry' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomLabelGraphicEntry',
            'CustomLabelPosition' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomLabelPosition',
            'CustomLabelTextBoxEntry' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomLabelTextBoxEntry',
            'CustomLabelTextEntry' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomLabelTextEntry',
            'CustomerImageUsage' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomerImageUsage',
            'CustomerReference' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomerReference',
            'CustomerSpecifiedLabelDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomerSpecifiedLabelDetail',
            'CustomsClearanceDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomsClearanceDetail',
            'CustomsDeclarationStatementDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomsDeclarationStatementDetail',
            'CustomsOptionDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\CustomsOptionDetail',
            'DangerousGoodsContainer' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DangerousGoodsContainer',
            'DangerousGoodsDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DangerousGoodsDetail',
            'DangerousGoodsShippersDeclarationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DangerousGoodsShippersDeclarationDetail',
            'DangerousGoodsSignatory' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DangerousGoodsSignatory',
            'DateRange' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DateRange',
            'DeleteShipmentRequest' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DeleteShipmentRequest',
            'DeleteTagRequest' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DeleteTagRequest',
            'DeliveryOnInvoiceAcceptanceDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DeliveryOnInvoiceAcceptanceDetail',
            'DestinationControlDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DestinationControlDetail',
            'Dimensions' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Dimensions',
            'DocTabContent' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DocTabContent',
            'DocTabContentBarcoded' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DocTabContentBarcoded',
            'DocTabContentZone001' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DocTabContentZone001',
            'DocTabZoneSpecification' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DocTabZoneSpecification',
            'DocumentFormatOptionsRequested' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\DocumentFormatOptionsRequested',
            'EMailDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\EMailDetail',
            'EMailLabelDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\EMailLabelDetail',
            'EMailRecipient' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\EMailRecipient',
            'EdtCommodityTax' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\EdtCommodityTax',
            'EdtExciseCondition' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\EdtExciseCondition',
            'EdtTaxDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\EdtTaxDetail',
            'EmailOptionsRequested' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\EmailOptionsRequested',
            'EtdDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\EtdDetail',
            'ExportDeclarationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ExportDeclarationDetail',
            'ExportDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ExportDetail',
            'ExpressFreightDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ExpressFreightDetail',
            'FreightAddressLabelDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\FreightAddressLabelDetail',
            'FreightBaseCharge' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\FreightBaseCharge',
            'FreightGuaranteeDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\FreightGuaranteeDetail',
            'FreightRateDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\FreightRateDetail',
            'FreightRateNotation' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\FreightRateNotation',
            'FreightShipmentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\FreightShipmentDetail',
            'FreightShipmentLineItem' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\FreightShipmentLineItem',
            'FreightSpecialServicePayment' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\FreightSpecialServicePayment',
            'GeneralAgencyAgreementDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\GeneralAgencyAgreementDetail',
            'HazardousCommodityContent' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HazardousCommodityContent',
            'HazardousCommodityDescription' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HazardousCommodityDescription',
            'HazardousCommodityInnerReceptacleDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HazardousCommodityInnerReceptacleDetail',
            'HazardousCommodityOptionDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HazardousCommodityOptionDetail',
            'HazardousCommodityPackagingDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HazardousCommodityPackagingDetail',
            'HazardousCommodityPackingDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HazardousCommodityPackingDetail',
            'HazardousCommodityQuantityDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HazardousCommodityQuantityDetail',
            'HoldAtLocationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HoldAtLocationDetail',
            'HomeDeliveryPremiumDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\HomeDeliveryPremiumDetail',
            'InternationalControlledExportDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\InternationalControlledExportDetail',
            'InternationalTrafficInArmsRegulationsDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\InternationalTrafficInArmsRegulationsDetail',
            'LabelSpecification' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\LabelSpecification',
            'LiabilityCoverageDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\LiabilityCoverageDetail',
            'LicenseOrPermitDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\LicenseOrPermitDetail',
            'LinearMeasure' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\LinearMeasure',
            'Localization' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Localization',
            'Measure' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Measure',
            'Money' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Money',
            'NaftaCertificateOfOriginDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\NaftaCertificateOfOriginDetail',
            'NaftaCommodityDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\NaftaCommodityDetail',
            'NaftaLowValueStatementDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\NaftaLowValueStatementDetail',
            'NaftaProducer' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\NaftaProducer',
            'NetExplosiveDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\NetExplosiveDetail',
            'Notification' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Notification',
            'NotificationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\NotificationDetail',
            'NotificationParameter' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\NotificationParameter',
            'Op900Detail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Op900Detail',
            'OperationalInstruction' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\OperationalInstruction',
            'PackageBarcodes' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PackageBarcodes',
            'PackageOperationalDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PackageOperationalDetail',
            'PackageRateDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PackageRateDetail',
            'PackageRating' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PackageRating',
            'PackageSpecialServicesRequested' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PackageSpecialServicesRequested',
            'Party' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Party',
            'Payment' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Payment',
            'Payor' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Payor',
            'PendingShipmentAccessDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PendingShipmentAccessDetail',
            'PendingShipmentAccessorDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PendingShipmentAccessorDetail',
            'PendingShipmentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PendingShipmentDetail',
            'PendingShipmentProcessingOptionsRequested' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PendingShipmentProcessingOptionsRequested',
            'PickupDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PickupDetail',
            'PrintedReference' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PrintedReference',
            'PriorityAlertDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\PriorityAlertDetail',
            'ProcessShipmentReply' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ProcessShipmentReply',
            'ProcessShipmentRequest' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ProcessShipmentRequest',
            'ProcessTagReply' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ProcessTagReply',
            'ProcessTagRequest' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ProcessTagRequest',
            'RadioactivityDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RadioactivityDetail',
            'RadionuclideActivity' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RadionuclideActivity',
            'RadionuclideDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RadionuclideDetail',
            'RateDiscount' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RateDiscount',
            'Rebate' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Rebate',
            'RecipientCustomsId' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RecipientCustomsId',
            'RecommendedDocumentSpecification' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RecommendedDocumentSpecification',
            'RegulatoryLabelContentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RegulatoryLabelContentDetail',
            'RequestedPackageLineItem' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RequestedPackageLineItem',
            'RequestedShipment' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\RequestedShipment',
            'ReturnAssociationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ReturnAssociationDetail',
            'ReturnEMailDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ReturnEMailDetail',
            'ReturnInstructionsDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ReturnInstructionsDetail',
            'ReturnShipmentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ReturnShipmentDetail',
            'Rma' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Rma',
            'ShipmentAuthorizationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentAuthorizationDetail',
            'ShipmentConfigurationData' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentConfigurationData',
            'ShipmentDryIceDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentDryIceDetail',
            'ShipmentDryIceProcessingOptionsRequested' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentDryIceProcessingOptionsRequested',
            'ShipmentEventNotificationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentEventNotificationDetail',
            'ShipmentEventNotificationSpecification' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentEventNotificationSpecification',
            'ShipmentLegRateDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentLegRateDetail',
            'ShipmentManifestDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentManifestDetail',
            'ShipmentNotificationFormatSpecification' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentNotificationFormatSpecification',
            'ShipmentOperationalDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentOperationalDetail',
            'ShipmentRateDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentRateDetail',
            'ShipmentRating' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentRating',
            'ShipmentReply' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentReply',
            'ShipmentSpecialServicesRequested' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShipmentSpecialServicesRequested',
            'ShippingDocument' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShippingDocument',
            'ShippingDocumentDispositionDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShippingDocumentDispositionDetail',
            'ShippingDocumentEMailDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShippingDocumentEMailDetail',
            'ShippingDocumentEMailRecipient' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShippingDocumentEMailRecipient',
            'ShippingDocumentFormat' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShippingDocumentFormat',
            'ShippingDocumentPart' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShippingDocumentPart',
            'ShippingDocumentPrintDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShippingDocumentPrintDetail',
            'ShippingDocumentSpecification' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ShippingDocumentSpecification',
            'SignatureOptionDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\SignatureOptionDetail',
            'SmartPostShipmentDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\SmartPostShipmentDetail',
            'SmartPostShipmentProcessingOptionsRequested' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\SmartPostShipmentProcessingOptionsRequested',
            'StringBarcode' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\StringBarcode',
            'Surcharge' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Surcharge',
            'Tax' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Tax',
            'TaxpayerIdentification' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\TaxpayerIdentification',
            'TrackingId' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\TrackingId',
            'TransactionDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\TransactionDetail',
            'UploadDocumentReferenceDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\UploadDocumentReferenceDetail',
            'ValidateShipmentRequest' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ValidateShipmentRequest',
            'ValidatedHazardousCommodityContent' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ValidatedHazardousCommodityContent',
            'ValidatedHazardousCommodityDescription' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ValidatedHazardousCommodityDescription',
            'ValidatedHazardousContainer' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\ValidatedHazardousContainer',
            'VariableHandlingChargeDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\VariableHandlingChargeDetail',
            'VariableHandlingCharges' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\VariableHandlingCharges',
            'Volume' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Volume',
            'Weight' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\Weight',
            'WebAuthenticationDetail' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\WebAuthenticationDetail',
            'WebAuthenticationCredential' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\WebAuthenticationCredential',
            'VersionId' => '\\Drupal\\commerce_fedex\\FedEx\\StructType\\VersionId',
        );
    }
}
