<?php

namespace Drupal\commerce_fedex\FedEx\EnumType;

/**
 * This class stands for RecommendedDocumentType EnumType
 * Meta informations extracted from the WSDL
 * - documentation: Type of documents that are recommended to be included with the shipment.
 * @subpackage Enumerations
 */
class RecommendedDocumentType
{
    /**
     * Constant for value 'ANTIQUE_STATEMENT_EUROPEAN_UNION'
     * @return string 'ANTIQUE_STATEMENT_EUROPEAN_UNION'
     */
    const VALUE_ANTIQUE_STATEMENT_EUROPEAN_UNION = 'ANTIQUE_STATEMENT_EUROPEAN_UNION';
    /**
     * Constant for value 'ANTIQUE_STATEMENT_UNITED_STATES'
     * @return string 'ANTIQUE_STATEMENT_UNITED_STATES'
     */
    const VALUE_ANTIQUE_STATEMENT_UNITED_STATES = 'ANTIQUE_STATEMENT_UNITED_STATES';
    /**
     * Constant for value 'ASSEMBLER_DECLARATION'
     * @return string 'ASSEMBLER_DECLARATION'
     */
    const VALUE_ASSEMBLER_DECLARATION = 'ASSEMBLER_DECLARATION';
    /**
     * Constant for value 'BEARING_WORKSHEET'
     * @return string 'BEARING_WORKSHEET'
     */
    const VALUE_BEARING_WORKSHEET = 'BEARING_WORKSHEET';
    /**
     * Constant for value 'CERTIFICATE_OF_SHIPMENTS_TO_SYRIA'
     * @return string 'CERTIFICATE_OF_SHIPMENTS_TO_SYRIA'
     */
    const VALUE_CERTIFICATE_OF_SHIPMENTS_TO_SYRIA = 'CERTIFICATE_OF_SHIPMENTS_TO_SYRIA';
    /**
     * Constant for value 'COMMERCIAL_INVOICE_FOR_THE_CARIBBEAN_COMMON_MARKET'
     * @return string 'COMMERCIAL_INVOICE_FOR_THE_CARIBBEAN_COMMON_MARKET'
     */
    const VALUE_COMMERCIAL_INVOICE_FOR_THE_CARIBBEAN_COMMON_MARKET = 'COMMERCIAL_INVOICE_FOR_THE_CARIBBEAN_COMMON_MARKET';
    /**
     * Constant for value
     * 'CONIFEROUS_SOLID_WOOD_PACKAGING_MATERIAL_TO_THE_PEOPLES_REPUBLIC_OF_CHINA'
     * @return string 'CONIFEROUS_SOLID_WOOD_PACKAGING_MATERIAL_TO_THE_PEOPLES_REPUBLIC_OF_CHINA'
     */
    const VALUE_CONIFEROUS_SOLID_WOOD_PACKAGING_MATERIAL_TO_THE_PEOPLES_REPUBLIC_OF_CHINA = 'CONIFEROUS_SOLID_WOOD_PACKAGING_MATERIAL_TO_THE_PEOPLES_REPUBLIC_OF_CHINA';
    /**
     * Constant for value 'DECLARATION_FOR_FREE_ENTRY_OF_RETURNED_AMERICAN_PRODUCTS'
     * @return string 'DECLARATION_FOR_FREE_ENTRY_OF_RETURNED_AMERICAN_PRODUCTS'
     */
    const VALUE_DECLARATION_FOR_FREE_ENTRY_OF_RETURNED_AMERICAN_PRODUCTS = 'DECLARATION_FOR_FREE_ENTRY_OF_RETURNED_AMERICAN_PRODUCTS';
    /**
     * Constant for value 'DECLARATION_OF_BIOLOGICAL_STANDARDS'
     * @return string 'DECLARATION_OF_BIOLOGICAL_STANDARDS'
     */
    const VALUE_DECLARATION_OF_BIOLOGICAL_STANDARDS = 'DECLARATION_OF_BIOLOGICAL_STANDARDS';
    /**
     * Constant for value
     * 'DECLARATION_OF_IMPORTED_ELECTRONIC_PRODUCTS_SUBJECT_TO_RADIATION_CONTROL_STANDA
     * RD'
     * @return string 'DECLARATION_OF_IMPORTED_ELECTRONIC_PRODUCTS_SUBJECT_TO_RADIATION_CONTROL_STANDARD'
     */
    const VALUE_DECLARATION_OF_IMPORTED_ELECTRONIC_PRODUCTS_SUBJECT_TO_RADIATION_CONTROL_STANDARD = 'DECLARATION_OF_IMPORTED_ELECTRONIC_PRODUCTS_SUBJECT_TO_RADIATION_CONTROL_STANDARD';
    /**
     * Constant for value 'ELECTRONIC_INTEGRATED_CIRCUIT_WORKSHEET'
     * @return string 'ELECTRONIC_INTEGRATED_CIRCUIT_WORKSHEET'
     */
    const VALUE_ELECTRONIC_INTEGRATED_CIRCUIT_WORKSHEET = 'ELECTRONIC_INTEGRATED_CIRCUIT_WORKSHEET';
    /**
     * Constant for value 'FILM_AND_VIDEO_CERTIFICATE'
     * @return string 'FILM_AND_VIDEO_CERTIFICATE'
     */
    const VALUE_FILM_AND_VIDEO_CERTIFICATE = 'FILM_AND_VIDEO_CERTIFICATE';
    /**
     * Constant for value 'INTERIM_FOOTWEAR_INVOICE'
     * @return string 'INTERIM_FOOTWEAR_INVOICE'
     */
    const VALUE_INTERIM_FOOTWEAR_INVOICE = 'INTERIM_FOOTWEAR_INVOICE';
    /**
     * Constant for value 'NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_ENGLISH'
     * @return string 'NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_ENGLISH'
     */
    const VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_ENGLISH = 'NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_ENGLISH';
    /**
     * Constant for value 'NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_FRENCH'
     * @return string 'NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_FRENCH'
     */
    const VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_FRENCH = 'NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_FRENCH';
    /**
     * Constant for value 'NAFTA_CERTIFICATE_OF_ORIGIN_SPANISH'
     * @return string 'NAFTA_CERTIFICATE_OF_ORIGIN_SPANISH'
     */
    const VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_SPANISH = 'NAFTA_CERTIFICATE_OF_ORIGIN_SPANISH';
    /**
     * Constant for value 'NAFTA_CERTIFICATE_OF_ORIGIN_UNITED_STATES'
     * @return string 'NAFTA_CERTIFICATE_OF_ORIGIN_UNITED_STATES'
     */
    const VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_UNITED_STATES = 'NAFTA_CERTIFICATE_OF_ORIGIN_UNITED_STATES';
    /**
     * Constant for value 'PACKING_LIST'
     * @return string 'PACKING_LIST'
     */
    const VALUE_PACKING_LIST = 'PACKING_LIST';
    /**
     * Constant for value 'PRINTED_CIRCUIT_BOARD_WORKSHEET'
     * @return string 'PRINTED_CIRCUIT_BOARD_WORKSHEET'
     */
    const VALUE_PRINTED_CIRCUIT_BOARD_WORKSHEET = 'PRINTED_CIRCUIT_BOARD_WORKSHEET';
    /**
     * Constant for value 'REPAIRED_WATCH_BREAKOUT_WORKSHEET'
     * @return string 'REPAIRED_WATCH_BREAKOUT_WORKSHEET'
     */
    const VALUE_REPAIRED_WATCH_BREAKOUT_WORKSHEET = 'REPAIRED_WATCH_BREAKOUT_WORKSHEET';
    /**
     * Constant for value 'STATEMENT_REGARDING_THE_IMPORT_OF_RADIO_FREQUENCY_DEVICES'
     * @return string 'STATEMENT_REGARDING_THE_IMPORT_OF_RADIO_FREQUENCY_DEVICES'
     */
    const VALUE_STATEMENT_REGARDING_THE_IMPORT_OF_RADIO_FREQUENCY_DEVICES = 'STATEMENT_REGARDING_THE_IMPORT_OF_RADIO_FREQUENCY_DEVICES';
    /**
     * Constant for value 'TOXIC_SUBSTANCES_CONTROL_ACT'
     * @return string 'TOXIC_SUBSTANCES_CONTROL_ACT'
     */
    const VALUE_TOXIC_SUBSTANCES_CONTROL_ACT = 'TOXIC_SUBSTANCES_CONTROL_ACT';
    /**
     * Constant for value
     * 'UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_NON_T
     * EXTILES'
     * @return string 'UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_NON_TEXTILES'
     */
    const VALUE_UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_NON_TEXTILES = 'UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_NON_TEXTILES';
    /**
     * Constant for value
     * 'UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_TEXTI
     * LES'
     * @return string 'UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_TEXTILES'
     */
    const VALUE_UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_TEXTILES = 'UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_TEXTILES';
    /**
     * Constant for value 'UNITED_STATES_NEW_WATCH_WORKSHEET'
     * @return string 'UNITED_STATES_NEW_WATCH_WORKSHEET'
     */
    const VALUE_UNITED_STATES_NEW_WATCH_WORKSHEET = 'UNITED_STATES_NEW_WATCH_WORKSHEET';
    /**
     * Constant for value 'UNITED_STATES_WATCH_REPAIR_DECLARATION'
     * @return string 'UNITED_STATES_WATCH_REPAIR_DECLARATION'
     */
    const VALUE_UNITED_STATES_WATCH_REPAIR_DECLARATION = 'UNITED_STATES_WATCH_REPAIR_DECLARATION';
    /**
     * Return true if value is allowed
     * @uses self::getValidValues()
     * @param mixed $value value
     * @return bool true|false
     */
    public static function valueIsValid($value)
    {
        return ($value === null) || in_array($value, self::getValidValues(), true);
    }
    /**
     * Return allowed values
     * @uses self::VALUE_ANTIQUE_STATEMENT_EUROPEAN_UNION
     * @uses self::VALUE_ANTIQUE_STATEMENT_UNITED_STATES
     * @uses self::VALUE_ASSEMBLER_DECLARATION
     * @uses self::VALUE_BEARING_WORKSHEET
     * @uses self::VALUE_CERTIFICATE_OF_SHIPMENTS_TO_SYRIA
     * @uses self::VALUE_COMMERCIAL_INVOICE_FOR_THE_CARIBBEAN_COMMON_MARKET
     * @uses self::VALUE_CONIFEROUS_SOLID_WOOD_PACKAGING_MATERIAL_TO_THE_PEOPLES_REPUBLIC_OF_CHINA
     * @uses self::VALUE_DECLARATION_FOR_FREE_ENTRY_OF_RETURNED_AMERICAN_PRODUCTS
     * @uses self::VALUE_DECLARATION_OF_BIOLOGICAL_STANDARDS
     * @uses self::VALUE_DECLARATION_OF_IMPORTED_ELECTRONIC_PRODUCTS_SUBJECT_TO_RADIATION_CONTROL_STANDARD
     * @uses self::VALUE_ELECTRONIC_INTEGRATED_CIRCUIT_WORKSHEET
     * @uses self::VALUE_FILM_AND_VIDEO_CERTIFICATE
     * @uses self::VALUE_INTERIM_FOOTWEAR_INVOICE
     * @uses self::VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_ENGLISH
     * @uses self::VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_FRENCH
     * @uses self::VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_SPANISH
     * @uses self::VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_UNITED_STATES
     * @uses self::VALUE_PACKING_LIST
     * @uses self::VALUE_PRINTED_CIRCUIT_BOARD_WORKSHEET
     * @uses self::VALUE_REPAIRED_WATCH_BREAKOUT_WORKSHEET
     * @uses self::VALUE_STATEMENT_REGARDING_THE_IMPORT_OF_RADIO_FREQUENCY_DEVICES
     * @uses self::VALUE_TOXIC_SUBSTANCES_CONTROL_ACT
     * @uses self::VALUE_UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_NON_TEXTILES
     * @uses self::VALUE_UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_TEXTILES
     * @uses self::VALUE_UNITED_STATES_NEW_WATCH_WORKSHEET
     * @uses self::VALUE_UNITED_STATES_WATCH_REPAIR_DECLARATION
     * @return string[]
     */
    public static function getValidValues()
    {
        return array(
            self::VALUE_ANTIQUE_STATEMENT_EUROPEAN_UNION,
            self::VALUE_ANTIQUE_STATEMENT_UNITED_STATES,
            self::VALUE_ASSEMBLER_DECLARATION,
            self::VALUE_BEARING_WORKSHEET,
            self::VALUE_CERTIFICATE_OF_SHIPMENTS_TO_SYRIA,
            self::VALUE_COMMERCIAL_INVOICE_FOR_THE_CARIBBEAN_COMMON_MARKET,
            self::VALUE_CONIFEROUS_SOLID_WOOD_PACKAGING_MATERIAL_TO_THE_PEOPLES_REPUBLIC_OF_CHINA,
            self::VALUE_DECLARATION_FOR_FREE_ENTRY_OF_RETURNED_AMERICAN_PRODUCTS,
            self::VALUE_DECLARATION_OF_BIOLOGICAL_STANDARDS,
            self::VALUE_DECLARATION_OF_IMPORTED_ELECTRONIC_PRODUCTS_SUBJECT_TO_RADIATION_CONTROL_STANDARD,
            self::VALUE_ELECTRONIC_INTEGRATED_CIRCUIT_WORKSHEET,
            self::VALUE_FILM_AND_VIDEO_CERTIFICATE,
            self::VALUE_INTERIM_FOOTWEAR_INVOICE,
            self::VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_ENGLISH,
            self::VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_FRENCH,
            self::VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_SPANISH,
            self::VALUE_NAFTA_CERTIFICATE_OF_ORIGIN_UNITED_STATES,
            self::VALUE_PACKING_LIST,
            self::VALUE_PRINTED_CIRCUIT_BOARD_WORKSHEET,
            self::VALUE_REPAIRED_WATCH_BREAKOUT_WORKSHEET,
            self::VALUE_STATEMENT_REGARDING_THE_IMPORT_OF_RADIO_FREQUENCY_DEVICES,
            self::VALUE_TOXIC_SUBSTANCES_CONTROL_ACT,
            self::VALUE_UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_NON_TEXTILES,
            self::VALUE_UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_TEXTILES,
            self::VALUE_UNITED_STATES_NEW_WATCH_WORKSHEET,
            self::VALUE_UNITED_STATES_WATCH_REPAIR_DECLARATION,
        );
    }
    /**
     * Method returning the class name
     * @return string __CLASS__
     */
    public function __toString()
    {
        return __CLASS__;
    }
}
